### ISSUE TITLE
Searching for linklint repo

### ISSUE THREAD

**Issue by mdlinville** [inkarkat/svn-extensions#1]
Hi, I know this isn't the right place but I can't see how else to get ahold of you. I use your fork of Linklint 2.3.5 from your website, but I can't find its source anywhere on Github. Can you point me in the right direction? I'd like to see about getting HTTPS support added to it.

**Comment by inkarkat** [comment]
I'm sorry that it took me more than two years to respond, but you unfortunately caught me in a very busy period &mdash; I've built a house and going through tough times at work.

I see that you've found [another linklint fork on GitHub](https://github.com/blech75/linklint). The sources of my modifications are still (exclusively) available at [my personal website](http://ingo-karkat.de/downloads/tools/linklint/). The ZIP file contains [all original files](http://www.linklint.org/), plus my modifications (as required by the GPL license) &mdash; it's all there, just not on GitHub.

I still use the tool (for my homepage), but haven't made any modifications to it for a long time, and probably won't have the time to extend it. It's kinda sad that the tool isn't maintained, as I still like it very much, and haven't come across a better alternative yet. If someone has tips, or even found a maintained fork, I'd be glad to hear about it!
